name: Bug Report
description: Create a bug report
title: "[Bug] <title>"
labels: ["Bug", "Needs Triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please check whether an issue (open and closed) already exists for the error you have encountered, or whether this problem is already mentioned in the documentation.
    options:
    - label: I have searched the existing issues (open and closed) and the documentation
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: In which environment Pi.Alert is installed.
    placeholder: |
        **OS**: Ubuntu 20.04
        **Environment**: Container or native
        **Plattform**: Arm, x86_32, x86_64
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
